const productsData = [
  {
    name: "Nike Air Max 90",
    price: 159,
    stars: 3,
    reviews: 0,
    seller: "Nike",
    image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/38e0a196-20d2-4820-9f3f-e44c98318039/air-max-90-zapatillas-56b7nN.png",
  },
  {
    name: "Adidas Samba OG",
    price: 120,
    stars: 2,
    reviews: 0,
    seller: "Adidas",
    image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/9b983d5bc09a4d4aba39a8bf011869ba_9366/zapatilla-samba-og.jpg",
  },
  {
    name: "Chuck Taylor All Star Well Worn",
    price: 95,
    stars: 0,
    reviews: 0,
    seller: "Converse",
    image: "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw131e68be/images/c_08/A07640C_C_08X1.jpg",
  },
  {
    name: "Easy Rider Vintage",
    price: 100,
    stars: 1,
    reviews: 0,
    seller: "Puma",
    image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_450,h_450/global/399028/01/sv01/fnd/EEA/fmt/png/Zapatillas-Easy-Rider-Vintage",
  },
  {
    name: "Club C 85",
    price: 100,
    stars: 5,
    reviews: 0,
    seller: "Reebok",
    image: "https://images.reebok.eu/reebok-zapatillas-club-c-85_19729666_44840555_200.jpg?c=1",
  },
  {
    name: "Chuck Taylor All Star Archive Flame",
    price: 80,
    stars: 3,
    reviews: 0,
    seller: "Converse",
    image: "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dwae1041ea/images/c_08/171130C_C_08X1.jpg",
  },
  {
    name: "Adidas GAZELLE",
    price: 110,
    stars: 3,
    reviews: 0,
    seller: "Adidas",
    image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/f0b88619d679465e91b1db1c1e387795_9366/gazelle.jpg",
  },
  {
    name: "Palermo Leather",
    price: 90,
    stars: 2,
    reviews: 0,
    seller: "Puma",
    image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_450,h_450/global/396464/01/sv01/fnd/EEA/fmt/png/Zapatillas-Palermo-Leather-unisex",
  },
  {
    name: "Nike Air Max Plus",
    price: 189,
    stars: 5,
    reviews: 0,
    seller: "Nike",
    image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/erzfadfpnzgkxt0gn2ya/air-max-plus-zapatillas-1gMZsK.png",
  }
];

export { productsData };